/*
Generates HTML from model m according to the following template.
*/

val myTemplate = DocumentTemplate( 
	"Requirements Document", 
	Text("Generated by " + 
	  " <a href=\"http://reqT.org\">reqT.org</a> " + 
	  ( new java.util.Date ) ), 
	Chapter("Context", Text(""), m => m / Context),
	Chapter("Features", Text(""), m => m / Feature),
	Chapter("Interfaces", Text(""), m => m / Interface)
)

m.toHtml(myTemplate).save("reqDoc.html")