/*
Generates HTML from model m according to the following template.
*/

val myTemplate = DocumentTemplate( 
	"Requirements Document", 
	Text("Generated by " + 
	  " <a href=\"http://reqT.org\">reqT.org</a> " + 
	  ( new java.util.Date ) ), 
	Chapter("Context", Text("System context"), m => (m / Context) \ Stakeholder),
	Chapter("Stakeholders", Text(""), m => m / Stakeholder),
	Chapter("Goals", Text(""), m => m / Goal),
	Chapter("Tasks", Text("Tasks to be supported"), m => m / Task)
)

m.toHtml(myTemplate).save("reqDoc.html")